version: '3'

services:
    
  reactapp:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"
    